services:
  cicdexample:
    image: ghcr.io/miwathan/cicdforexam:latest
    restart: unless-stopped
    ports:
     - 8001:8001
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    depends_on:
      - mssql-db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"] 
      interval: 20s
      timeout: 3s
      retries: 3

  mssql-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    container_name: mssql2022
    ports:
      - "1533:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=MyPass123$
    volumes:
      - mssql-data:/var/opt/mssql

  watchtower:
    image: nickfedor/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_POLL_INTERVAL: 20
      WATCHTOWER_CLEANUP: "true"
    command: --label-enable

volumes:
  mssql-data: